WITH GET_CNT AS (
    SELECT MEMBER_ID, COUNT(REST_ID) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
), GET_MEMBER_ID AS (
    SELECT MEMBER_ID
    FROM GET_CNT 
    WHERE CNT = (
        SELECT MAX(CNT) 
        FROM GET_CNT
    )
)
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d')
FROM MEMBER_PROFILE M
INNER JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
INNER JOIN GET_MEMBER_ID G ON M.MEMBER_ID = G.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT
